services:
  redis:
    env_file:
      - ./apps/backend/.env
    image: redis:7
    ports:
      - "6379:6379"
    # command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    networks:
      - ondc

  api:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.backend
    ports:
      - "3000:3000"
    env_file:
      - ./apps/backend/.env
    restart: always
    depends_on:
      - redis
    networks:
      - ondc

  web:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile.frontend
    env_file:
      - ./apps/frontend/.env
    ports:
      - "3020:80"
    restart: always
    networks:
      - ondc

networks:
  ondc:
