ONDC:ONEST10 - Work Opportunities:
  summary: ONDC:ONEST10 - Work Opportunities
  description: >
    Job Hub is acting as provider platform (BPP) which hosts the jobs and Worker Hub is acting as seeker platform (BAP) which helps the workers to find jobs.
    <br/><br/>
        PRD: ONEST - Work Opportunity : <a href="https://docs.google.com/document/d/1VydDAqtzjj1jDrJzX4hwZSlYyJsA_bSOJIKYTWxNSpQ">link</a>
    <br/><br/>
    BRD: ONEST - Work Opportunities : <a href="https://docs.google.com/document/d/1cuvt_w9qSv7XpLXpY4KCq5gmrsQSqF8e3VLxOhpfO0g">link</a>
    <br/><br/>
    Taxonomy: ONEST - Work Opportunities : <a href="https://docs.google.com/spreadsheets/d/1Go22ou013hE-fxpjMd_XuM111l8x8TuMsF_nsjvB3so">link</a>
  example_set:
    $ref: "./Services_Work_Opportunities_yaml/index.yaml"